### ISSUE TITLE
EPIC v1.0.0

### ISSUE THREAD

**Issue by pabloitu** [cseptesting/floatcsep#40]
- [ ] Consolidate Docker environment manager for models
- [ ] Include database storage feature
- [ ] Create Reproducibility Testing repositories, which provide experimental data from:
  - [ ] RELM
  - [ ] Italy 2010
  - [ ] New Zealand 2010
  - [ ] Japan 2009
  - [ ] Global experiment
- [ ] Implement the Italy 2024 LIVE Floating Experiment
- [ ] Implement the Europe OEF testing
