### ISSUE TITLE
Epic: version 0.2.0

### ISSUE THREAD

**Issue by pabloitu** [cseptesting/floatcsep#6]
The new release should include and address the following features and issues, respectively: 

- [x] Logging (#7)
  - [x] Persistence and storage of log for a given experiment.
  - [x] Define scopes of DEBUG and INFO. Which should go in a retrospective or live
experiment?
  - [x] #20
- [x] #9
  - [x] #10 
  - [x] Decouple Experiment and Results file/handling from main classes
- [x] #12 
- [x] #17
- [x] #19
- [x] #22
- [x] #24
- [x] Remove functionalities that belong to pyCSEP and PR to pyCSEP gh
- [x] #28
- [x] #30
- [x] #33
- [x] #35
- [x] #39
- [x] Set-up automatic versioning

**Comment by pabloitu** [comment]
completed
